---

- name: Install New Relic dependencies
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  retries: 2
  register: apt_result
  until: apt_result is succeeded
  with_items:
    - apt-transport-https
    - apt-utils

- name: Ensure New Relic PGP key is known to the server
  become: yes
  apt_key:
    id: "{{ sansible_newrelic_integration_infra_apt_key }}"
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  retries: 2
  register: apt_result
  until: apt_result is succeeded

- name: Add New Relic APT repository
  become: yes
  apt_repository:
    repo: "{{ sansible_newrelic_integration_infra_apt_repo }}"
    update_cache: yes

- name: Install New Relic Infra
  become: yes
  apt:
    pkg: "newrelic-infra={{ sansible_newrelic_integration_infra_version }}"
    state: present
  retries: 2
  register: apt_result
  until: apt_result is succeeded

- name: Ensure New Relic Infra log directory exists
  become: yes
  file:
    group: "{{ sansible_newrelic_integration_infra_group }}"
    owner: "{{ sansible_newrelic_integration_infra_user }}"
    path: /var/log/newrelic
    state: directory

- name: Ensure New Relic service is disabled
  become: yes
  service:
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
    enabled: no
    name: newrelic-infra
